[package]
name = "craftmine-authentication-service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.13.0"
argon2 = "0.5.3"
env_logger = "0.11.10"
flexi_logger = "0.31.9"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
log = "0.4.32"
opentelemetry-appender-tracing = "0.32.0"
opentelemetry_sdk = { version = "0.32.1", features = ["logs"] }
rand_core = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.23", features = ["registry"] }
uuid = { version = "1.23.3", features = ["v4"] }

[dependencies.sea-orm]
version = "2.0.0-rc.40"
features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "schema-sync", "entity-registry"]
