#include "../../labs/A03Mesh2D/Mesh2DTransforms.h"
#include <cgclib/math/Mat4.h>
#include <cgclib/math/Transforms.h>
#include <cgclib/math/Vec3.h>
#include <cgclib/math/Vec4.h>
#include <unity/unity.h>

#define RELATIVE_ERROR 0.01f

#define TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(delta, expected, actual)                                               \
    TEST_ASSERT_FLOAT_WITHIN((delta * expected), expected, actual)

void setUp(void)
{
}
void tearDown(void)
{
}

static void test_ObjectToCamera_0_Degrees(void)
{
    float      degrees = 0;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ObjectToCamera(time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], 0.5f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

static void test_ObjectToCamera_90_Degrees(void)
{
    float      degrees = 90;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ObjectToCamera(time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], -0.788178563f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], -0.615446627f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], 0.0331233516f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], 0.615446627f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], -0.788178563f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], 0.498901635);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

static void test_ObjectToCamera_180_Degrees(void)
{
    float      degrees = 180;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ObjectToCamera(time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], 0.242450833f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], 0.970163703f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], -0.495611370f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], -0.970163703f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], 0.242450833f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], 0.0661011785f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

static void test_ObjectToCamera_270_Degrees(void)
{
    float      degrees = 270;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ObjectToCamera(time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], 0.404203773f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], -0.914668977f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], -0.0987885892f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], 0.914668977f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], 0.404203773f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], -0.490143657f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

static void test_ModelToWindow_90_Degrees_256x256(void)
{
    float      degrees = 90;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ModelToWindow(256, 256, time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], -100.886856f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], -78.7771683f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], 132.239792f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], 78.7771683);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], -100.886856f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], 191.859406f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

static void test_ModelToWindow_90_Degrees_1920x1080(void)
{
    float      degrees = 90;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ModelToWindow(1920, 1080, time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], -425.616425f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], -332.341187f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], 977.886597f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], 332.341187);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], -425.616425f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], 809.406860f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

static void test_ModelToWindow_90_Degrees_1080x1920(void)
{
    float      degrees = 90;
    float      time    = degrees * 1e5f;
    const Mat4 p       = ModelToWindow(1080, 1920, time);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[0], -425.616425f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[1], -332.341187f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[2], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[3], 557.886597f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[4], 332.341187);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[5], -425.616425f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[6], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[7], 1229.40686f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[8], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[9], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[10], 1.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[11], 0.0f);

    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[12], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[13], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[14], 0.0f);
    TEST_ASSERT_FLOAT_WITHIN_RELATIVE_ERROR(RELATIVE_ERROR, p.m[15], 1.0f);
}

int main(void)
{
    UNITY_BEGIN();

    RUN_TEST(test_ObjectToCamera_0_Degrees);
    RUN_TEST(test_ObjectToCamera_90_Degrees);
    RUN_TEST(test_ObjectToCamera_180_Degrees);
    RUN_TEST(test_ObjectToCamera_270_Degrees);

    RUN_TEST(test_ModelToWindow_90_Degrees_256x256);
    RUN_TEST(test_ModelToWindow_90_Degrees_1920x1080);
    RUN_TEST(test_ModelToWindow_90_Degrees_1080x1920);
    return UNITY_END();
}
